using Microsoft.AspNetCore.Identity;

namespace EmployeeManagementSystem.API.Models
{
    public class ApplicationUser : IdentityUser
    {
        public int? EmployeeId { get; set; }
        public virtual Employee? Employee { get; set; }

        // Navigation property for AuditLogs generated by this user
        public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();
    }
}
